### ISSUE TITLE
Download .deb 404

### ISSUE THREAD

**Issue by Kriz300** [Darthzner/Server-y-Cliente-XMPP#1]
Al momento de hacerle docker build . al cliente se produce el siguiente error fatal:

```
--(fecha) (hora)-- https://download.igniterealtime.org/spark/dailybuilds/spark_2_9_3-20200928.deb
Resolving download.igniterealtime.org (download.igniterealtime.org)... 52.58.216.59
Connecting to download.igniterealtime.org (download.igniterealtime.org)|52.58.216.59|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
(fecha) (hora) ERROR 404: Not Found.

```
Al ingresar en [igniterealtime](https://www.igniterealtime.org/downloads/) no se encuentra disponible para descargar la versión 2.9.3 del software utilizado como cliente y en su [github](https://github.com/igniterealtime/Spark) el ultimo release es la version 2.9.2.

Por favor actualizar a la brevedad.

**Comment by Darthzner** [comment]
Solucionado el error de la versión, lo que ocurre es que al momento de hacer el proyecto, la ultima versión de este era la 2.9.3, pero al parecer tuvo problemas y la bajaron. Con respecto al git, en este caso el cliente tiene problemas en su github oficial, debido a servidores dados de baja para la descarga de algunos archivos, por esto se hace la descarga directamente de la pagina. De todas formas gracias por reportarlo.
